# Generated by Django 5.1.2 on 2024-11-15 02:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('point', models.IntegerField(default=0)),
                ('scheduled_classes', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.JSONField()),
                ('tuition', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_account', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_depositor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=32, unique=True)),
                ('login_pw', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('tutor', 'Tutor'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Classtime',
            fields=[
                ('classtime_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('day', models.CharField(choices=[('sun', 'Sun'), ('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri'), ('sat', 'Sat')], default='mon', max_length=3)),
                ('time', models.TimeField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('daily_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contents', models.TextField()),
                ('memo', models.TextField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.parent'),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20)),
                ('unit', models.JSONField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('k', '유치원'), ('e1', '초1'), ('e2', '초2'), ('e3', '초3'), ('e4', '초4'), ('e5', '초5'), ('e6', '초6'), ('m1', '중1'), ('m2', '중2'), ('m3', '중3'), ('h1', '고1'), ('h2', '고2'), ('h3', '고3'), ('n', 'N수생'), ('u', '대학생'), ('a', '성인')], default='a', max_length=2)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.parent')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('grade', models.JSONField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student'),
        ),
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('supplements_id', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('file_name', models.CharField(max_length=50)),
                ('file_data', models.BinaryField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tutor'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('date', models.DateTimeField(auto_created=True)),
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('due', models.DateTimeField(default=django.utils.timezone.now)),
                ('contents', models.TextField()),
                ('state', models.BooleanField(default=False)),
                ('daily_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.daily')),
                ('tutor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tutor')),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount'),
        ),
        migrations.CreateModel(
            name='D_Day',
            fields=[
                ('d_day_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount')),
            ],
        ),
    ]
