# Generated by Django 5.1.2 on 2024-11-21 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_useraccount_created_at_alter_useraccount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='class',
            name='student',
        ),
        migrations.RemoveField(
            model_name='class',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='classtime',
            name='type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.CharField(choices=[('k', '유치원'), ('e1', '초1'), ('e2', '초2'), ('e3', '초3'), ('e4', '초4'), ('e5', '초5'), ('e6', '초6'), ('m1', '중1'), ('m2', '중2'), ('m3', '중3'), ('h1', '고1'), ('h2', '고2'), ('h3', '고3'), ('n', 'N수생'), ('u', '대학생'), ('a', '성인')], default='a', max_length=2),
        ),
        migrations.AddField(
            model_name='class',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.parent'),
        ),
        migrations.AddField(
            model_name='class',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='tutor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tutor'),
        ),
        migrations.AddField(
            model_name='classtime',
            name='is_supply_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='day',
            field=models.CharField(choices=[('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], default='mon', max_length=3),
        ),
    ]
