# Generated by Django 5.1.2 on 2024-11-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_class_parent_remove_class_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='payment_status',
            field=models.JSONField(null=True),
        ),
    ]
