# Generated by Django 5.1.2 on 2024-11-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_class_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='scheduled_classes',
            field=models.JSONField(null=True),
        ),
    ]
