# Generated by Django 5.1.2 on 2024-11-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_class_scheduled_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
