# Generated by Django 5.1.2 on 2024-12-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_class_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='daily_id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='due',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='state',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='file_data',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='file_name',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classtime',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='classtime',
            name='student',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='assignment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='dictation_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='last_progress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='mock_exam_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='parent_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='progress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='student',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='tutor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tutor'),
        ),
        migrations.AddField(
            model_name='daily',
            name='word_test_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='tutor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tutor'),
        ),
        migrations.AddField(
            model_name='supplements',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplements',
            name='tutor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tutor'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
