# Generated by Django 5.1.2 on 2024-12-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_assignment_contents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='tutor_id',
            new_name='tutor',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='tutor_id',
            new_name='tutor',
        ),
        migrations.RenameField(
            model_name='classtime',
            old_name='class_id',
            new_name='related_class',
        ),
        migrations.RenameField(
            model_name='classtime',
            old_name='student',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='d_day',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='assignment',
            new_name='assignment_details',
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='student',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='tutor_id',
            new_name='tutor',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='tutor_id',
            new_name='tutor',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='class_id',
            new_name='related_class',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='type',
            new_name='score_type',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='supplements',
            old_name='tutor_id',
            new_name='tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='user_id',
            new_name='user',
        ),
    ]
