# Generated by Django 5.1.2 on 2024-12-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_assignment_assignment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='description',
            new_name='assignment',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='tutor',
            new_name='tutor_id',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='parent',
            new_name='parent_id',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='tutor',
            new_name='tutor_id',
        ),
        migrations.RenameField(
            model_name='classtime',
            old_name='related_class',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='classtime',
            old_name='student_name',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='d_day',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='assignment_details',
            new_name='assignment',
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='student_name',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='tutor',
            new_name='tutor_id',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='tutor',
            new_name='tutor_id',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='related_class',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='score_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parent',
            new_name='parent_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='supplements',
            old_name='tutor',
            new_name='tutor_id',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='user',
            new_name='user_id',
        ),
    ]
