# Generated by Django 5.1.2 on 2024-12-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_description_assignment_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='classtime',
            name='student',
        ),
    ]
