# Generated by Django 5.1.2 on 2024-12-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_classtime_date_remove_classtime_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_day',
            name='date',
        ),
        migrations.AddField(
            model_name='d_day',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='d_day',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
