# Generated by Django 5.1.2 on 2024-12-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_d_day_date_d_day_color_alter_d_day_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_day',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
